[workspace]
resolver = "2"
members = [
    "benches",
    "codegen/*",
    "dialects/*",
    "eval",
    "frontend/*",
    "hir",
    "hir-analysis",
    "hir-macros",
    "hir-symbol",
    "hir-transform",
    "hir-type",
    "midenc",
    "midenc-compile",
    "midenc-debug",
    "midenc-driver",
    "midenc-session",
    "midenc-wasm",
    "sdk/*",
    "tools/*",
    "tests/integration",
    "tests/integration-node",
]
exclude = [
    "sdk/.cargo",
    "tests/rust-apps-wasm",
    "cargo-ext/tests/data",
    "examples",
]

[workspace.package]
version = "0.4.1"
rust-version = "1.90"
authors = ["Miden contributors"]
description = "An intermediate representation and compiler for Miden Assembly"
repository = "https://github.com/0xMiden/compiler"
homepage = "https://github.com/0xMiden/compiler"
documentation = "https://github.com/0xMiden/compiler"
categories = ["compilers"]
keywords = ["compiler", "miden"]
license = "MIT"
readme = "README.md"
edition = "2021"
publish = false

[workspace.dependencies]
anyhow = { version = "1.0", default-features = false }
bitflags = "2.4"
bitvec = { version = "1.0", default-features = false, features = ["alloc"] }
blink-alloc = { version = "0.3", default-features = false, features = [
    "alloc",
    "nightly",
] }
clap = { version = "4.5", default-features = false, features = [
    "derive",
    "std",
    "env",
    "help",
    "suggestions",
    "error-context",
] }
cranelift-entity = "0.120"
compact_str = { version = "0.9", default-features = false }
env_logger = "0.11"
hashbrown = { version = "0.15", features = ["nightly"] }
hashbrown_old_nightly_hack = { package = "hashbrown", version = "0.14.5", features = [
    "allocator-api2",
    "nightly",
] }
Inflector = "0.11"
intrusive-collections = "0.9"
inventory = "0.3"
log = "0.4"

# Miden Dependencies
miden-assembly = { version = "0.17.1", default-features = false }
miden-core = { version = "0.17.1", default-features = false }
miden-debug-types = { version = "0.17.1", default-features = false }
miden-assembly-syntax = { version = "0.17.1", default-features = false }
miden-formatting = { version = "0.1", default-features = false }
miden-lib = { version = "0.11.0", default-features = false, features = [
    "with-debug-info",
] }
miden-objects = { version = "0.11.0", default-features = false }
miden-processor = { version = "0.17.1", default-features = false }
miden-stdlib = { version = "0.17.1", default-features = false, features = [
    "with-debug-info",
] }
miden-mast-package = { version = "0.17.1", default-features = false }
miette = { package = "miden-miette", version = "8.0", default-features = false, features = ["derive"] }
paste = "1.0"
parking_lot = "0.12"
parking_lot_core = "0.9"
petgraph = "0.6"
pretty_assertions = "1.0"
proptest = "1.4"
proc-macro2 = "1.0"
quote = "1.0"
rustc-hash = { version = "2.0", default-features = false }
semver = { version = "1.0", default-features = false }
serde = { version = "1.0", default-features = false, features = [
    "serde_derive",
    "alloc",
    "rc",
] }

smallvec = { version = "1.14", default-features = false, features = [
    "union",
    "const_generics",
    "const_new",
    "drain_filter",
] }
syn = { version = "2.0", features = [
    "full",
    "parsing",
    "derive",
    "extra-traits",
    "printing",
] }
thiserror = { package = "miden-thiserror", version = "1.0" }
toml = { version = "0.8", features = ["preserve_order"] }
tokio = { version = "1.39.2", features = ["rt", "time", "macros", "rt-multi-thread"] }
wat = "1.0.69"
wasmparser = { version = "0.227", default-features = false, features = [
    "features",
    "component-model",
    "validate",
    "simd",
] }

# Workspace crates
midenc-codegen-masm = { version = "0.4.1", path = "codegen/masm", default-features = false }
midenc-dialect-arith = { version = "0.4.1", path = "dialects/arith", default-features = false }
midenc-dialect-hir = { version = "0.4.1", path = "dialects/hir", default-features = false }
midenc-dialect-scf = { version = "0.4.1", path = "dialects/scf", default-features = false }
midenc-dialect-cf = { version = "0.4.1", path = "dialects/cf", default-features = false }
midenc-dialect-ub = { version = "0.4.1", path = "dialects/ub", default-features = false }
midenc-hir = { version = "0.4.1", path = "hir", default-features = false }
midenc-hir-analysis = { version = "0.4.1", path = "hir-analysis", default-features = false }
midenc-hir-eval = { version = "0.4.1", path = "eval", default-features = false }
midenc-hir-macros = { version = "0.4.1", path = "hir-macros", default-features = false }
midenc-hir-symbol = { version = "0.4.1", path = "hir-symbol", default-features = false }
midenc-hir-transform = { version = "0.4.1", path = "hir-transform", default-features = false }
midenc-hir-type = { version = "0.4.2", path = "hir-type", default-features = false }
midenc-frontend-wasm = { version = "0.4.1", path = "frontend/wasm", default-features = false }
midenc-compile = { version = "0.4.1", path = "midenc-compile", default-features = false }
midenc-driver = { version = "0.4.1", path = "midenc-driver", default-features = false }
midenc-debug = { version = "0.4.1", path = "midenc-debug", default-features = false }
midenc-session = { version = "0.4.1", path = "midenc-session", default-features = false }
cargo-miden = { version = "0.4.1", path = "tools/cargo-miden" }
miden-integration-tests = { path = "tests/integration" }
midenc-expect-test = { path = "tools/expect-test" }

[patch.crates-io]
miden-assembly = { path = "../miden-vm/assembly" }
miden-assembly-syntax = { path = "../miden-vm/assembly-syntax" }
miden-core = { path = "../miden-vm/core" }
miden-debug-types = { path = "../miden-vm/crates/debug/types" }
miden-utils-diagnostics = { path = "../miden-vm/crates/utils/diagnostics" }
miden-processor = { path = "../miden-vm/processor" }
miden-stdlib = { path = "../miden-vm/stdlib" }
miden-mast-package = { path = "../miden-vm/package" }
miden-air = { path = "../miden-vm/air" }
#miden-client = { git = "https://github.com/0xMiden/miden-client", rev = "f98ae87fc3f77e269c3c1e412d1b8ac650aa6fe3" }
#miden-lib = { git = "https://github.com/0xMiden/miden-base", rev = "64ba4d0f8a077dd7d8f2643ebafa155f95b1c241" }


[profile.dev]
lto = false
# Needed for 'inventory' to work
codegen-units = 1

[profile.release]
opt-level = 2
debug = true
codegen-units = 1
lto = "fat"

# The following crates are always built with optimizations
[profile.test.package.proptest]
opt-level = 3

[profile.test.package.rand_chacha]
opt-level = 3

[profile.dev.package.dissimilar]
opt-level = 3

[profile.dev.package.regex-syntax]
opt-level = 3

[profile.dev.package.onig]
opt-level = 3

[profile.dev.package.miden-crypto]
opt-level = 3

# Speed up the local network integration tests (proving times)
# ============================================================
[profile.dev.package.miden-processor]
opt-level = 3

[profile.dev.package.miden-prover]
opt-level = 3

[profile.dev.package.winter-prover]
opt-level = 3

[profile.dev.package.miden-client]
opt-level = 3

[profile.dev.package.miden-lib]
opt-level = 3

[profile.dev.package.miden-tx]
opt-level = 3
# ============================================================
