[package]
name = "miden-integration-tests"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
cargo-util = "0.2"
env_logger.workspace = true
midenc-expect-test.workspace = true
filetime = "0.2.23"
glob = "0.3.1"
log.workspace = true
miden-assembly.workspace = true
miden-core.workspace = true
miden-mast-package.workspace = true
miden-protocol = { workspace = true, features = ["std"] }
miden-processor.workspace = true
miden-debug = { workspace = true, features = ["proptest"] }
midenc-dialect-arith.workspace = true
midenc-dialect-cf.workspace = true
midenc-dialect-hir.workspace = true
midenc-frontend-wasm.workspace = true
midenc-hir.workspace = true
midenc-hir-eval.workspace = true
midenc-codegen-masm.workspace = true
midenc-session.workspace = true
midenc-compile.workspace = true
cargo-miden.workspace = true
miden-standards = { workspace = true, features = ["std"] }
wasmprinter = "0.227"
proptest.workspace = true
sha2 = "0.10"
walkdir = "2.5.0"

[dev-dependencies]
# Use local paths for dev-only dependency to avoid relying on crates.io during packaging
blake3 = "1.5"
concat-idents = "1.1"
